In [3]:
import numpy as np

In [6]:
x = np.array([2,5,6])
print(x)
print(x.shape)
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(b.shape)

[2 5 6]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [22]:
c = np.arange(1,10,0.2)
print(c)
print(c.shape)
d = np.linspace(1,10,100)
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.

In [18]:
print(c.ndim)

1


In [24]:
print(c.reshape(3,5,3))

[[[1.  1.2 1.4]
  [1.6 1.8 2. ]
  [2.2 2.4 2.6]
  [2.8 3.  3.2]
  [3.4 3.6 3.8]]

 [[4.  4.2 4.4]
  [4.6 4.8 5. ]
  [5.2 5.4 5.6]
  [5.8 6.  6.2]
  [6.4 6.6 6.8]]

 [[7.  7.2 7.4]
  [7.6 7.8 8. ]
  [8.2 8.4 8.6]
  [8.8 9.  9.2]
  [9.4 9.6 9.8]]]


In [27]:
np.random.randint(-156,236,(3,3,5))

array([[[ -10,  124,  128,  221,  214],
        [  73,  156,  -51,  214,   61],
        [ 105,  142,  109,  110, -154]],

       [[  62,  178,  135,   54,   -7],
        [  95,  175,  107, -130,  183],
        [  56,  -97, -116,  -44,   84]],

       [[ -49,   48,   -3,   49,  -40],
        [-118,  214,   -2,  167,  -67],
        [ -94,  111,  209, -101,  148]]])

In [28]:
x = np.array([
    [2,3,4],
    [5,6,7]
])


y = np.array([
    [4,8,10],
    [8,7,9]
    ])

In [32]:
print(x+y)
print(x-y)
print(x*y)
print(x%y)
print(x/y)
print(x*2)
print(x%2)


[[ 6 11 14]
 [13 13 16]]
[[-2 -5 -6]
 [-3 -1 -2]]
[[ 8 24 40]
 [40 42 63]]
[[2 3 4]
 [5 6 7]]
[[0.5        0.375      0.4       ]
 [0.625      0.85714286 0.77777778]]
[[ 4  6  8]
 [10 12 14]]
[[0 1 0]
 [1 0 1]]


In [36]:
print(x.dot(y.T))
print(np.matmul(x,y.T))
print(x @ y.T)

[[ 72  73]
 [138 145]]
[[ 72  73]
 [138 145]]
[[ 72  73]
 [138 145]]


In [38]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.argmax())
print(x.argmin())

27
[ 7  9 11]
[ 9 18]
4.5
1.707825127659933
2
7
5
0


In [39]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866 ]]
[[-0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225]]
[[-2.18503986 -0.14254654  1.15782128]
 [-3.38051501 -0.29100619  0.87144798]]


In [40]:
#indexing
print(x[0,0]) #first row first column
print(x[0,:]) #first row all columns
print(x[:,0])
print(x[0:2,0:2])
print(x[:2,:2])
print(x[:2])

2
[2 3 4]
[2 5]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]
[[2 3 4]
 [5 6 7]]
